version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: afera-postgres

    environment:
      POSTGRES_DB: afera_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data: